import { LearningMetric, MetricDefinition } from '../types';

export const mockLearningMetrics: LearningMetric[] = [
    {
        id: 'lm-1',
        name: 'Courses Completed',
        category: 'Training',
        value: 42,
        target: 50,
        unit: 'courses',
        trend: 'up',
        sparkline: [28, 30, 33, 36, 38, 40, 42],
    },
    {
        id: 'lm-2',
        name: 'Certifications Earned',
        category: 'Certification',
        value: 18,
        target: 25,
        unit: 'certs',
        trend: 'up',
        sparkline: [10, 12, 13, 14, 16, 17, 18],
    },
    {
        id: 'lm-3',
        name: 'Skill Growth Index',
        category: 'Skills',
        value: 87,
        target: 95,
        unit: '%',
        trend: 'up',
        sparkline: [72, 75, 78, 80, 83, 85, 87],
    },
    {
        id: 'lm-4',
        name: 'Training Hours',
        category: 'Training',
        value: 320,
        target: 400,
        unit: 'hrs',
        trend: 'up',
        sparkline: [200, 230, 250, 270, 290, 305, 320],
    },
    {
        id: 'lm-5',
        name: 'Knowledge Score',
        category: 'Assessment',
        value: 78,
        target: 85,
        unit: '%',
        trend: 'neutral',
        sparkline: [74, 75, 76, 77, 78, 78, 78],
    },
    {
        id: 'lm-6',
        name: 'Mentoring Sessions',
        category: 'Collaboration',
        value: 64,
        target: 80,
        unit: 'sessions',
        trend: 'up',
        sparkline: [40, 45, 48, 52, 56, 60, 64],
    },
    {
        id: 'lm-7',
        name: 'Tech Talk Participation',
        category: 'Engagement',
        value: 92,
        target: 100,
        unit: '%',
        trend: 'up',
        sparkline: [70, 75, 80, 84, 87, 90, 92],
    },
    {
        id: 'lm-8',
        name: 'Onboarding Completion',
        category: 'Onboarding',
        value: 95,
        target: 100,
        unit: '%',
        trend: 'up',
        sparkline: [80, 83, 86, 89, 91, 93, 95],
    },
    {
        id: 'lm-9',
        name: 'Learning Path Progress',
        category: 'Training',
        value: 68,
        target: 90,
        unit: '%',
        trend: 'up',
        sparkline: [40, 45, 50, 55, 60, 64, 68],
    },
    {
        id: 'lm-10',
        name: 'Cross-team Collaboration',
        category: 'Collaboration',
        value: 72,
        target: 85,
        unit: '%',
        trend: 'down',
        sparkline: [78, 77, 76, 75, 74, 73, 72],
    },
];

export const mockMetricDefinitions: MetricDefinition[] = [
    {
        id: 'MTR-001',
        name: 'Sprint Velocity',
        metricType: 'velocity',
        metricClass: 'A',
        threshold: 200,
        updateFrequency: 'weekly',
        rangeMin: 0,
        rangeMax: 500,
        account: 'Optibyte Solutions',
        market: 'North America',
        project: 'Platform Core',
        team: 'Team Alpha',
        createdAt: new Date('2025-12-01'),
    },
    {
        id: 'MTR-002',
        name: 'Code Quality Score',
        metricType: 'quality',
        metricClass: 'A',
        threshold: 85,
        updateFrequency: 'daily',
        rangeMin: 0,
        rangeMax: 100,
        account: 'Optibyte Solutions',
        market: 'Europe',
        project: 'Analytics Suite',
        team: 'Team Beta',
        createdAt: new Date('2025-12-05'),
    },
    {
        id: 'MTR-003',
        name: 'Bug Resolution Rate',
        metricType: 'bug_rate',
        metricClass: 'B',
        threshold: 90,
        updateFrequency: 'daily',
        rangeMin: 0,
        rangeMax: 100,
        account: 'TechCorp Inc.',
        market: 'Asia Pacific',
        project: 'Mobile App',
        team: 'Team Gamma',
        createdAt: new Date('2025-12-10'),
    },
    {
        id: 'MTR-004',
        name: 'Customer Satisfaction',
        metricType: 'quality',
        metricClass: 'A',
        threshold: 4.0,
        updateFrequency: 'monthly',
        rangeMin: 0,
        rangeMax: 5,
        account: 'DataFlow Systems',
        market: 'North America',
        project: 'Platform Core',
        team: 'Team Delta',
        createdAt: new Date('2025-12-15'),
    },
    {
        id: 'MTR-005',
        name: 'Deployment Success Rate',
        metricType: 'deployment_frequency',
        metricClass: 'B',
        threshold: 95,
        updateFrequency: 'weekly',
        rangeMin: 0,
        rangeMax: 100,
        account: 'Optibyte Solutions',
        market: 'Europe',
        project: 'Analytics Suite',
        team: 'Team Epsilon',
        createdAt: new Date('2025-12-20'),
    },
];

// Helper to generate next metric ID
export function getNextMetricId(existingMetrics: MetricDefinition[]): string {
    const maxNum = existingMetrics.reduce((max, m) => {
        const num = parseInt(m.id.replace('MTR-', ''), 10);
        return num > max ? num : max;
    }, 0);
    return `MTR-${String(maxNum + 1).padStart(3, '0')}`;
}
