import { SLADefinition, SLABreach } from '../types';

export const mockSLADefinitions: SLADefinition[] = [
    {
        id: 's1',
        name: 'Response Time SLA',
        description: 'Customer support first response time',
        teamId: '1',
        teamName: 'Team Alpha',
        metricType: 'response_time',
        targetValue: 2,
        currentValue: 1.8,
        unit: 'hours',
        thresholdWarning: 1.6,
        thresholdCritical: 1.8,
        status: 'met',
        breachCount: 0,
        isActive: true,
    },
    {
        id: 's2',
        name: 'Resolution Time SLA',
        description: 'Average ticket resolution time',
        teamId: '1',
        teamName: 'Team Alpha',
        metricType: 'resolution_time',
        targetValue: 24,
        currentValue: 28,
        unit: 'hours',
        thresholdWarning: 20,
        thresholdCritical: 22,
        status: 'missed',
        breachCount: 3,
        isActive: true,
    },
    {
        id: 's3',
        name: 'Deployment Frequency',
        description: 'Number of deployments per week',
        teamId: '3',
        teamName: 'Team Gamma',
        metricType: 'deployment_frequency',
        targetValue: 10,
        currentValue: 9,
        unit: 'deployments/week',
        thresholdWarning: 8,
        thresholdCritical: 7,
        status: 'at_risk',
        breachCount: 1,
        isActive: true,
    },
    {
        id: 's4',
        name: 'Code Quality',
        description: 'Minimum code quality score',
        teamId: '2',
        teamName: 'Team Beta',
        metricType: 'quality',
        targetValue: 90,
        currentValue: 92.5,
        unit: '%',
        thresholdWarning: 85,
        thresholdCritical: 80,
        status: 'met',
        breachCount: 0,
        isActive: true,
    },
];

export const mockSLABreaches: SLABreach[] = [
    {
        id: 'b1',
        slaId: 's2',
        slaName: 'Resolution Time SLA',
        teamId: '1',
        breachStart: new Date(Date.now() - 48 * 60 * 60 * 1000),
        breachEnd: null,
        severity: 'critical',
        actualValue: 28,
        targetValue: 24,
        variance: 4,
        isResolved: false,
    },
    {
        id: 'b2',
        slaId: 's3',
        slaName: 'Deployment Frequency',
        teamId: '3',
        breachStart: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
        breachEnd: null,
        severity: 'warning',
        actualValue: 9,
        targetValue: 10,
        variance: 1,
        isResolved: false,
    },
];
