import { Team, TeamMember } from '../types';

export const mockTeams: Team[] = [
    {
        id: '1',
        name: 'Team Alpha',
        description: 'Core platform development team',
        teamLead: {
            id: 'u1',
            name: 'Alice Johnson',
            email: 'alice@example.com',
            role: 'PROJECT',
            avatar: '/avatars/alice.jpg',
        },
        memberCount: 8,
        performance: 92,
        isActive: true,
        parentTeamId: null,
        accountId: 'a1',
        createdAt: new Date('2025-01-15'),
    },
    {
        id: '2',
        name: 'Team Beta',
        description: 'Mobile app development',
        teamLead: {
            id: 'u2',
            name: 'Bob Smith',
            email: 'bob@example.com',
            role: 'PROJECT',
            avatar: '/avatars/bob.jpg',
        },
        memberCount: 6,
        performance: 78,
        isActive: true,
        parentTeamId: '1',
        accountId: 'a1',
        createdAt: new Date('2025-02-01'),
    },
    {
        id: '3',
        name: 'Team Gamma',
        description: 'DevOps and infrastructure',
        teamLead: {
            id: 'u3',
            name: 'Charlie Brown',
            email: 'charlie@example.com',
            role: 'PROJECT',
            avatar: '/avatars/charlie.jpg',
        },
        memberCount: 10,
        performance: 85,
        isActive: true,
        parentTeamId: null,
        accountId: 'a1',
        createdAt: new Date('2025-01-20'),
    },
    {
        id: '4',
        name: 'Team Delta',
        description: 'QA and testing',
        teamLead: {
            id: 'u4',
            name: 'Diana Prince',
            email: 'diana@example.com',
            role: 'PROJECT',
            avatar: '/avatars/diana.jpg',
        },
        memberCount: 5,
        performance: 65,
        isActive: true,
        parentTeamId: '1',
        accountId: 'a1',
        createdAt: new Date('2025-02-10'),
    },
    {
        id: '5',
        name: 'Team Epsilon',
        description: 'Data engineering',
        teamLead: {
            id: 'u5',
            name: 'Edward Kim',
            email: 'edward@example.com',
            role: 'PROJECT',
            avatar: '/avatars/edward.jpg',
        },
        memberCount: 7,
        performance: 88,
        isActive: true,
        parentTeamId: null,
        accountId: 'a1',
        createdAt: new Date('2025-01-25'),
    },
];

export const mockTeamMembers: TeamMember[] = [
    {
        id: 'tm1',
        teamId: '1',
        user: {
            id: 'u1',
            name: 'Alice Johnson',
            email: 'alice@example.com',
            role: 'PROJECT',
            avatar: '/avatars/alice.jpg',
        },
        roleInTeam: 'Lead',
        joinedAt: new Date('2025-01-15'),
    },
    {
        id: 'tm2',
        teamId: '1',
        user: {
            id: 'u6',
            name: 'Frank Miller',
            email: 'frank@example.com',
            role: 'TEAM',
            avatar: '/avatars/frank.jpg',
        },
        roleInTeam: 'Senior Engineer',
        joinedAt: new Date('2025-01-20'),
    },
    {
        id: 'tm3',
        teamId: '1',
        user: {
            id: 'u7',
            name: 'Grace Hopper',
            email: 'grace@example.com',
            role: 'TEAM',
            avatar: '/avatars/grace.jpg',
        },
        roleInTeam: 'Software Engineer',
        joinedAt: new Date('2025-02-01'),
    },
];
